export const AUTH_DISCARD_TOKEN = 'AUTH_DISCARD_TOKEN';
export const API_REQUEST_SEND = 'API_REQUEST_SEND';

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";


export const GET_TODO_LIST = "GET_TODO_LIST";
export const GET_TODO_DETAIL = "GET_TODO_DETAIL";
export const ADD_TODO_LIST = "ADD_TODO_LIST";
export const EDIT_TODO_LIST = "EDIT_TODO_LIST";
export const DELETE_TODO_LIST = "DELETE_TODO_LIST";

export const RESPONSE_MESSAGE = "RESPONSE_MESSAGE";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
